name: Build and publish a new package release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install build
      run: python -m pip install --upgrade build

    - uses: olegtarasov/get-tag@v2.1
      id: tagName

    - name: Build wheels
      env:
        VERSION: ${{ steps.tagName.outputs.tag }}
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
